language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - composer run-script test

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - bash <(curl -s https://codecov.io/bash)