language: php

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - composer run-script test
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)